def get_stock_list():
    list_of_names = [
        ("SPI Energy", "SPI", 0),
        ("Exxon Mobil", "XOM", 0),
        ("First Solar", "FSLR", 0),
        ("Plug Power", "PLUG", 0),
        ("Devon Energy", "DVN", 0),
        ("SolarEdge Technologies", "SEDG", 0),
        ("Apache", "APA", 0),
        ("Chesapeake Energy", "CHK", 0),
        ("Marathon Petroleum", "MPC", 0),
        ("NextEra Energy", "NEE", 0),
        ("Canadian Solar", "CSIQ", 0),
        ("Enbridge", "ENB", 0),
        ("Kosmos Energy", "KOS", 0),
        ("Williams Companies", "WMB", 0),
        ("Ballard Power Systems", "BLDP", 0),
        ("JinkoSolar", "JKS", 0),
        ("Valaris", "VAL", 0),
        ("Bonanza Creek Energy", "BCEI", 0),
        ("Callon Petroleum", "CPE", 0),
        ("Chevron", "CVX", 0),
        ("Energy Transfer", "ET", 0),
        ("Peabody Energy", "BTU", 0),
        ("Sun Power", "SPWR", 0),
        ("FuelCell Energy", "FCEL", 0),
        ("Endphase Energy", "ENPH", 0),
        ("Marathon Oil", "MRO", 0),
        ("Pembina Pipeline", "PBA", 0),
        ("Sunrun", "RUN", 0),
        ("Occidental Petroleum", "OXY", 0),
        ("Murphy Oil", "MUR", 0),
        ("Phillips 66", "PSX", 0),
        ("Southern", "SO", 0),
        ("Diamondback Energy", "FANG", 0),
        ("Valero Energy", "VLO", 0),
        ("Cabot Oil & Gas", "COG", 0),
        ("Diamond Offshore", "DO", 0),
        ("Enterprise Products Partners", "EPD", 0),
        ("ONEOK", "OKE", 0),
        ("Baker Hughes", "BKR", 0),
        ("ConocoPhillips", "COP", 0),
        ("Halliburton", "HAL", 0),
        ("Schlumberger", "SLB", 0),
        ("Western Midstream Partners", "WES", 0),
        ("Black Shore Minerals", "BSM", 0),
        ("National Oilwell Varco", "NOV", 0),
        ("Petroleo Brailio", "PBR", 0),
        ("AES Corp.", "AES", 0),
        ("Canadian Natural Resources", "CNQ", 0),
        ("Holly Energy Partners", "HEP", 0),
        ("Magellan Midstream Partners", "MMP", 0),
        ("MPLX LP", "MPLX", 0),
        ("Advanced Emissions Solutions", "ADES", 0),
        ("American Superconductor", "AMSC", 0),
        ("DTE Energy", "DTE", 0),
        ("TechnipFMC", "FTI", 0),
        ("Geospace Technologies", "GEOS", 0),
        ("Natural Gas Services Group", "NGS", 0),
        ("PBF Energy", "PEN", 0),
        ("Total", "TOT", 0),
        ("Taronis Technologies", "TRNX", 0),
        ("Consol Energy", "CEIX", 0),
        ("Comstock Resources", "CRK", 0),
        ("Now", "DNOW", 0),
        ("EOG Resources", "EOG", 0),
        ("Equinor", "EQNR", 0),
        ("EQT Corp.", "EQT", 0),
        ("Exterran", "EXTN", 0),
        ("Murphy USA", "MUSA", 0),
        ("NACCO Industries", "NC", 0),
        ("Oasis Midstream Partners", "OMP", 0),
        ("Phillips 66 Partners", "PSXP", 0),
        ("Transocean", "RIG", 0),
        ("Targa Resources", "TRGP", 0),
        ("TC Energy", "TRP", 0),
        ("Viper Energy Partners", "VNOM", 0),
        ("VOC Energy Trust", "VOC", 0),
        ("WPX Energy", "WPX", 0),
        ("Ameresco, Inc.", "AMRC", 0),
        ("Arch Resources", "ARCH", 0),
        ("Alliance Resource Partners", "ARLP", 0),
        ("Archrock, Inc.", "AROC", 0),
        ("Continental Resources", "CLR", 0),
        ("CMS Energy", "CMS", 0),
        ("Cheniere Energy Partners", "CQP", 0),
        ("CVR Energy", "CVI", 0),
        ("Concho Resources", "CXO", 0),
        ("Cosan", "CZZ", 0),
        ("DCP Midstream", "DCP", 0),
        ("Dril-Quip", "DRQ", 0),
        ("EnLink Midstream", "ENLC", 0),
        ("Eversource Energy", "ES", 0),
        ("Entergy", "ETR", 0)
        # ...
    ]

    return list_of_names
